---
- name: add group "tomcat"
  group: name=tomcat

- name: add user "tomcat"
  user: name=tomcat group=tomcat

- name: Extract archive
  unarchive: src={{src_file}} dest={{dest_dir}}

- name: Change ownership of Tomcat installation
  file: path=/usr/local/tomcat8/ owner=tomcat group=tomcat state=directory recurse=yes

- name: Install tomcat native
  script: tomcat-native.sh

- name: Configure Tomcat server
  template: src=server.xml dest=/usr/local/tomcat8/conf/
  notify: restart tomcat

- name: Install Tomcat init script
  copy: src=tomcat-initscript.sh dest=/etc/init.d/tomcat8 mode=0755

- name: Start Tomcat
  service: name=tomcat8 state=started enabled=yes
